ARG PYTHON_VERSION=3.11

FROM python:${PYTHON_VERSION}-slim AS bulder

RUN apt-get update \
    && apt-get install -y \
        build-essential \
        wget \
        htop \
        libgl1 \
        libglib2.0-0

WORKDIR /app
COPY . .

ENV PYTHONPATH=/app/src
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONBUFFERED=1
ENV PYTHONFAULTHANDLER=1

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir poetry

RUN poetry config virtualenvs.create false \
    && poetry lock \
    && poetry install --with=dev --no-cache --no-interaction --no-ansi

CMD ["sleep", "infinity"]
