name: Build & Push
run-name: >
  Build & Push
  ${{ github.event_name == 'workflow_dispatch' && inputs.force && '(forced)' || github.event.workflow_run.head_branch }}

on:
  workflow_run:
    workflows: ["Check & Test"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      force:
        description: "Force build (without push to registry, for PR/manual test)"
        type: boolean
        default: false

concurrency:
  group: build-push-${{ github.event.workflow_run.head_branch || github.ref_name }}
  cancel-in-progress: false

permissions:
  contents: read
  packages: write

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  docker-main:
    needs: []
    if: >
      (
        github.event_name == 'workflow_dispatch' &&
        inputs.force == true
      )
      ||
      (
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.head_branch == 'main' &&
        github.event.repository.fork == false
      )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.sha }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            name=${{ github.repository }},enable=${{ github.event.repository.fork == false }}
            ${{ env.GHCR_IMAGE }}
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}},enable=false
            type=match,pattern=v(.*),group=1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: |
            linux/arm64
          push: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main' && github.event.repository.fork == false }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          no-cache: true
