from typing import Protocol, Any
from collections.abc import Callable

class WorkerPool(Protocol):
    async def run(self, func: Callable[..., Any], /, *args: Any, **kwargs: Any) -> Any: ...
    async def shutdown(self) -> None: ...
